const colors = {
  light: {
    text: "#1A0A2E",
    tint: "#7C3AED",
    background: "#F5F0FF",
    foreground: "#1A0A2E",
    card: "#EDE5FF",
    cardForeground: "#1A0A2E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#DDD5FF",
    secondaryForeground: "#1A0A2E",
    muted: "#EDE5FF",
    mutedForeground: "#6D28D9",
    accent: "#A78BFA",
    accentForeground: "#1A0A2E",
    destructive: "#F43F5E",
    destructiveForeground: "#FFFFFF",
    border: "#C4B5FD",
    input: "#C4B5FD",
    success: "#10B981",
    surface: "#EDE5FF",
    surfaceElevated: "#DDD5FF",
    overlay: "rgba(26,10,46,0.5)",
  },
  dark: {
    text: "#F0ECFF",
    tint: "#A78BFA",
    background: "#0B0714",
    foreground: "#F0ECFF",
    card: "#160D22",
    cardForeground: "#F0ECFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1F1232",
    secondaryForeground: "#F0ECFF",
    muted: "#1F1232",
    mutedForeground: "#A492D4",
    accent: "#A78BFA",
    accentForeground: "#0B0714",
    destructive: "#F43F5E",
    destructiveForeground: "#FFFFFF",
    border: "#2D1F4A",
    input: "#2D1F4A",
    success: "#22C55E",
    surface: "#160D22",
    surfaceElevated: "#1F1232",
    overlay: "rgba(11,7,20,0.8)",
  },
  radius: 14,
};

export default colors;
